### ISSUE TITLE
verified creator

### ISSUE THREAD

**Issue by marcobucci77** [gruntwork-io/terragrunt-action#22]
**Describe the solution you'd like**
I'm using a GitHub Enterprise and a policy says that only GitHub Actions with "Verified Creator" can be used, Can you  add the "Verified Creator" to this GitHub Actions please?

**Comment by denis256** [comment]
Appeared `Verified creator` check on action page:
![image](https://github.com/gruntwork-io/terragrunt-action/assets/10694338/2f3fa872-b06a-444c-9687-11bf2d88dd54)
