### ISSUE TITLE
Terragrunt output isn't commented on pushes

### ISSUE THREAD

**Issue by aiell0** [gruntwork-io/terragrunt-action#25]
**Describe the bug**
If a push is made to an open PR, the terragrunt output is not commented in the PR when `tg_comment: 1`.

**To Reproduce**
1. Open a PR that will run a github action with this action inside of it. Have `tg_comment: 1` to indicate that there is to be a comment on the PR. Ensure that this action can be run on pull request opens and on pushes.
2. Push a change to the PR.
3. Notice that the plan is not printed into the PR.

**Expected behavior**
The output of the terragrunt command should be in the PR.

**Nice to have**
- [ ] Terminal output
- [ ] Screenshots

**Versions**
- Terragrunt Action version: v1
- Environment details (Terragrunt version, Terraform version, etc.):
  - Terraform: 1.5.7
  - Terragrunt: 0.51.7

**Additional context**
This is useful if the developer sees something in the plan that needs to be changed and wants to update the code in the PR. With this bug, it looks like the plan isn't changing. They have to go into the github run to actually see it.

**Comment by aiell0** [comment]
Turns out the issue was that I needed the `synchronize` event on my github action for this to work. This works as expected.

**Comment by nicholasarvelo** [comment]
> Turns out the issue was that I needed the `synchronize` event on my github action for this to work. This works as expected.

@aiell0 I am running into issues getting my output commented on the PR. Could you provide additional details about your fix? Are you referring to `on.pull_request: [synchronize]`?
