### ISSUE TITLE
Change root->runner breaks pipeline if action is not tag to patch version

### ISSUE THREAD

**Issue by miguellgramacho96** [gruntwork-io/terragrunt-action#35]
When declaring the usage of gruntwork-io/terragrunt-action@v1, out of the sudden my pipeline breaks with the following error:

```
2023-11-07 10:22:47 Starting Terragrunt Action
error: could not lock config file /github/home/.gitconfig: Permission denied
2023-11-07 10:22:47 Finished Terragrunt Action execution
```

This happens given that I pass a script via INPUT_PRE_EXEC_1 that uses root.
I would argue that bumping a patch for this type of change is not correct.. as it's not a backward compatible change.

I can fix the issue importing the action as follows gruntwork-io/terragrunt-action@v1.0.10.

**Comment by denis256** [comment]
Hello,
wanted to confirm if in action `gruntwork-io/terragrunt-action@bug/permissions-fix-34` this issue was fixed, before merging in 

Need to think how to add some basic tests to action execution
