### ISSUE TITLE
Add Support for installing OpenTofu instead of Terraform

### ISSUE THREAD

**Issue by rstuhlmuller** [gruntwork-io/terragrunt-action#53]
### Describe the solution you'd like
Add the ability for the terragrunt-action to optionally install and use OpenTofu instead of Terraform. This could be achieved by introducing a new input parameter, e.g., use_opentofu, which when set to true, would trigger the installation and use of OpenTofu instead of Terraform.

### Describe alternatives you've considered

- Create a separate action for OpenTofu: Instead of modifying the existing terragrunt-action, create a new action specifically designed for OpenTofu. This would keep the terragrunt-action focused on Terraform, while providing a separate solution for OpenTofu users.
- Fork the terragrunt-action: Create a fork of the terragrunt-action repository and modify it to support OpenTofu. This would allow for easier maintenance and updates, but would require users to switch to the forked version.
### Additional context
OpenTofu is a drop-in replacement for Terraform, aiming to provide faster and more efficient execution of Terraform configurations. By adding support for OpenTofu in the terragrunt-action, users would have the option to leverage the performance benefits of OpenTofu while still utilizing the existing action and its features.

It's worth noting that introducing OpenTofu support might require additional testing and validation to ensure compatibility with the existing action and its workflows. Additionally, documentation updates would be necessary to guide users on how to enable and use OpenTofu with the action.

**Comment by kvendingoldo** [comment]
At this moment if you need to have a support of Terraform as well as OpenTofu (and Terragrunt :) ) in one tool you can use https://github.com/tofuutils/tenv which my team wrote some months ago. A lot of users switched to that tool to unify version management in the world of Terraform. 

You're welcome to open any issues or contribute to [tenv](https://github.com/tofuutils/tenv).

**Comment by jhoblitt** [comment]
It seems inevitable that opentofu's behavior will start to deverge, even if it is only the exact cadence at which bugfixes are released. As the community starts to switch to opentofu, either this action will need to be updated or forked.

**Comment by ZachGoldberg** [comment]
Hi, Zach from Gruntwork here. We fully intend to support OpenTofu in terragrunt-action.  We'll likely get to it in the next couple of weeks, in the interrim PRs are welcome!

**Comment by jhoblitt** [comment]
@ZachGoldberg Hi Zach, is the plan to switch from `tfenv` to `tenv` to support both tf/tofu going forward?

**Comment by ZachGoldberg** [comment]
Hi @jhoblitt -- we're midway through migrating to [mise](https://mise.jdx.dev/) across all Gruntwork repos, I anticipate we'll refactor the dependency installation mechanism in `terragrunt-action` to follow the same pattern

**Comment by jhoblitt** [comment]
This is the first I've heard of `mise`.  Its plugin [registry](https://github.com/mise-plugins/registry?tab=readme-ov-file) links to the [asdf opentofu plugin](https://github.com/virtualroot/asdf-opentofu).  Is any dev work needed to make `mise` work with tofu or should it be ready to go?

**Comment by ZachGoldberg** [comment]
Mise works with tofu out of the box at this point!  We're using it in a number of places, its very elegant/straightforward.

**Comment by arsci** [comment]
OpenTofu support has been added and released in [v2.1.0](https://github.com/gruntwork-io/terragrunt-action/releases/tag/v2.1.0)
