### ISSUE TITLE
Migrate from tfenv to tenv

### ISSUE THREAD

**Issue by kvendingoldo** [gruntwork-io/terragrunt-action#56]
Hi! I saw that you're using tfenv in this repository. It's a really good tool, but it does not support OpenTofu and Terragrunt. My team designed a successor of tenv that support Terraform, Terragrunt and OpenTofu. It will be a good idea to migrate into it in due to the growing popularity of OpenTofu.
url: https://github.com/tofuutils/tenv

**Comment by ZachGoldberg** [comment]
Hi @kvendingoldo !  Thanks for writing in.  We're actively working on replacing `tfenv` throughout the stack, you should see updates here shortly.  I believe the team has settled on [mise](https://mise.jdx.dev/) as the replacement tool-installer of choice.
