### ISSUE TITLE
Action fails with error jq: Argument list too long

### ISSUE THREAD

**Issue by cristianr-ps** [gruntwork-io/terragrunt-action#71]
**Describe the bug**
The action fails to post a comment on the pull request with the error: 
`/action/main.sh: line 79: /usr/bin/jq: Argument list too long`

**To Reproduce**
Use the action to perform a run-all plan operation against a terragrunt configuration with hundreds of resources.
My configuration tree contains 387 for example. `terragrunt run-all state list | wc -l`

**Expected behavior**
The action should not fail and a comment should be posted to the pull request.

**Versions**
- Terragrunt Action version:
- Environment details (Terragrunt version, Terraform version, etc.):

**Comment by palmithor** [comment]
I am facing this issue as well.
